/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./components/404.vue')['default']
    About: typeof import('./components/About.vue')['default']
    Archives: typeof import('./components/Archives.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    Blog: typeof import('./components/Blog.vue')['default']
    Categories: typeof import('./components/Categories.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    Login: typeof import('./components/Login.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    ManagementDashboard: typeof import('./components/ManagementDashboard.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RightSide: typeof import('./components/layouts/RightSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubTags: typeof import('./components/subpages/SubTags.vue')['default']
    Tags: typeof import('./components/Tags.vue')['default']
  }
}
